# Generated by Django 4.2.10 on 2024-02-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0011_rename_user_types_userprofileinfo_user_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='user_type',
            new_name='user_types',
        ),
    ]
