# Generated by Django 4.2.10 on 2024-02-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0012_rename_user_type_userprofileinfo_user_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='user_types',
            new_name='user_type',
        ),
    ]
